--- 
Rubygoo::App: 
  :bg_color: :Purple
Rubygoo::Container: 
  :bg_color: :none
Rubygoo::Widget: 
  :font: VeraBd.ttf
  :font_size: 30
  :color: :LightGray
  :focus_color: :FireBrick
  :bg_color: :Gray
  :border_color: :FireBrick
  :hover_color:
    - 55
    - 55
    - 55
    - 155
Rubygoo::Label: 
  :bg_color: :none
  :border_color: :none
Rubygoo::CheckBox:
  :checked_color: :DarkViolet
Rubygoo::TextField:
  :fg_color: :FireBrick
  :bg_color: :Gray
  :bg_select_color: :FireBrick
  :fg_select_color: :Snow
  :border_color: :Black
Rubygoo::MouseCursor:
  :color: :Snow
  :mouse_cursor: cursor.png
Rubygoo::Dialog:
  :bg_color: :MediumPurple
IntroMode:
  :bg_color: :Black
:main_menu: 
  :bg_color: :Black
