--- 
Rubygoo::App: 
  :bg_color: 
    - 73
    - 77
    - 77
    - 255
Rubygoo::Container: 
  :bg_color: :none
Rubygoo::Widget: 
  :font: Vera.ttf
  :font_size: 20
  :color: :White
  :focus_color: :LightSlateGray
  :bg_color: 
    - 102
    - 126
    - 157
    - 255
  :border_color: 
    - 36
    - 44
    - 119
    - 255
  :hover_color: 
    - 55
    - 55
    - 55
    - 155
Rubygoo::Label: 
  :bg_color: :none
  :border_color: :none
Rubygoo::CheckBox:
  :checked_color: :LightSlateGray
Rubygoo::TextField:
  :fg_color: :Black
  :bg_select_color: :DarkSlateBlue
  :fg_select_color: :Snow
  :border_color: :DarkSlateBlue
Rubygoo::MouseCursor:
  :color: :DarkSlateGray
  :mouse_cursor: cursor.png
Rubygoo::Dialog:
  :bg_color: :LightSlateGray
IntroMode:
  :bg_color: :Black
:main_menu: 
  :bg_color: :Black
